// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2F_BxAO63dDGf7lNlBnuQErsuD1LYLH0',
    appId: '1:881991093724:web:53038703d3f6ec3aeb5319',
    messagingSenderId: '881991093724',
    projectId: 'watchlist-app-3108e',
    authDomain: 'watchlist-app-3108e.firebaseapp.com',
    storageBucket: 'watchlist-app-3108e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxkKxtEj5vaYeoLZmiP4hDQ_kw7FZRIQ',
    appId: '1:881991093724:android:db7c870285174f6feb5319',
    messagingSenderId: '881991093724',
    projectId: 'watchlist-app-3108e',
    storageBucket: 'watchlist-app-3108e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPv8-Ty9alrvE-qfbGnkrOaQDIBGl7cHg',
    appId: '1:881991093724:ios:5ff5fd06332f4c8deb5319',
    messagingSenderId: '881991093724',
    projectId: 'watchlist-app-3108e',
    storageBucket: 'watchlist-app-3108e.appspot.com',
    iosClientId: '881991093724-e4un8dobghr0gokjj2nssi2ahq8b0atg.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPv8-Ty9alrvE-qfbGnkrOaQDIBGl7cHg',
    appId: '1:881991093724:ios:5ff5fd06332f4c8deb5319',
    messagingSenderId: '881991093724',
    projectId: 'watchlist-app-3108e',
    storageBucket: 'watchlist-app-3108e.appspot.com',
    iosClientId: '881991093724-e4un8dobghr0gokjj2nssi2ahq8b0atg.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlist',
  );
}
